services:
  database:
    build: ./Database
    container_name: tournament-manager-database-container
    restart: always
    ports:
      - 1433:1433
    volumes:
      - db-data:/var/opt/mssql
    environment:
      - ACCEPT_EULA="Y"
      - MSSQL_SA_PASSWORD=Welcome01!
      - SA_PID=TournamentManager
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P Welcome01! -Q 'SELECT 1' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
  server:
    build: ./Server
    container_name: tournament-manager-server-container
    ports:
      - 8080:8080
    environment:
      - LOGGING__LOGLEVEL__DEFAULT=Warning
    depends_on:
      database:
        condition: service_healthy
    develop:
      watch:
      - action: rebuild
        path: ./Server
  api-test:
    container_name: tournament-manager-api-test-container
    build: 
      context: ./Client
      dockerfile: Dockerfile.api
    environment:
      - CYPRESS_APIURL=http://server:8080/api
    depends_on:
      - server
    develop:
      watch:
      - action: sync+restart
        path: ./Client/apps/tournament-manager-api-test
        target: /api-test/apps/tournament-manager-api-test
volumes:
  db-data: