///////////////////////////////////////////////////////////
// This file is generated by TournamentManager.Tools.Cli //
///////////////////////////////////////////////////////////

export * from './generated/sport'
export * from './generated/table-tennis-handicap'
export * from './generated/table-tennis-tournament-type'
