name: DockerDeploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      # Database
      - name: Build Database
        uses: docker/build-push-action@v5
        with:
          context: ./Database
          load: true
      - name: Build and push Database
        uses: docker/build-push-action@v5
        with:
          context: ./Database
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:Database
      # Server
      - name: Build and test Server
        uses: docker/build-push-action@v5
        with:
          context: ./Server
          target: build
          load: true
      - name: Build and push Server
        uses: docker/build-push-action@v5
        with:
          context: ./Server
          push: true
          target: final
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:Server
      
